#!/usr/bin/env python
'''
  youtube to mplayer

    single search:

      yts
      search: roots manuva
      choose: 2

      yts tom waits
      choose: 2

    playlist:

      yts -p
      search: bartok
      choose: 0
      search: miley cyrus
      choose: 2
      search: [play][save]['']

    play from file:
        yts -f playlist.ytspl

    direct play:
      yts -i http://www.youtube.com/watch?v=P0Rccv5dCgc -i 1nfKpiGwRVo
'''

import os, re, urllib, webbrowser
from subprocess import Popen, PIPE

try:
    import readline
    readline.parse_and_bind('tab: complete')
    readline.set_completer_delims('')
except:
    pass

def directvid(url):
    ''' take a watch url or ID and return a video url '''
    if not url:
        return
    if not url.startswith('http://'):
        url = 'http://www.youtube.com/watch?v=%s' % url
    w = urllib.urlopen(url).readlines()
    fnd = ''
    for line in w:
        if '"video_id":' in line and '"t":' in line:
            line = line.split(',')
            line = [i for i in line if '"t":' in i or '"video_id"' in i]
            line = [i.strip().split('"') for i in line]
            line = ['%s=%s' % (i[1], i[3]) for i in line]
            fnd = 'http://youtube.com/get_video.php?%s' % '&'.join(line)
            break
    return fnd

def search(srch):
    ''' given a search string, return a list of tuples (title, url) '''
    if not srch:
        return
    print srch
    url = 'http://www.youtube.com/results?search_query=%s'
    res = urllib.urlopen(url % urllib.quote_plus(srch)).readlines()
    vids = []
    for line in res:
        if 'href="/watch?' in line:
            attrs = re.findall('[a-z]+=\"[^\"]*\"', line)
            attrs = [i.split("=",1) for i in attrs]
            d = {}
            for i in attrs:
                d[i[0]] = i[1][1:-1]
            try:
                vid = (d['title'], 'http://www.youtube.com%s' % d['href'])
            except:
                pass
            if vid not in vids:
                vids.append(vid)
    return vids

def choose(k):
    if not k:
        return False
    for i, j in enumerate(k):
        print '%3s\t%s' % (i, j[0])
    try:
        n = k[int(raw_input('choose: '))]
    except:
        return False
    print n[1]
    return n[1]

def juke():
    vids = []
    while True:
        s = raw_input('search: ')
        if s == 'play':
            break
        elif s == 'save':
            while True:
                filename = raw_input('filename: ')
                if not filename:
                    return
                if not filename.endswith('.ytspl'):
                    if not os.path.basename(filename):
                        print 'no file name!'
                        continue
                    filename = '%s.ytspl' % filename
                if os.path.exists(filename):
                    print 'file exists!'
                    continue
                fh = open(filename, 'w')
                fh.write(os.linesep.join(vids))
                fh.write(os.linesep)
                fh.close()
                print '%s written.' % filename
                return
        elif not s:
            return
        else:
            vids.append(choose(search(s)))
        vids = [i for i in vids if i]
    for vid in vids:
        mplayer(directvid(vid), opts.video)

def mplayer(url, video):
    if not url:
        return
    print url
    cmd = ['mplayer', '-nolirc', '-prefer-ipv4', '-idx', '-quiet']
    if not video:
        cmd += ['-vo', 'null']
    try:
        p = Popen(cmd + [url], stdout=PIPE, stderr=PIPE)
        p.wait()
    except:
        pass
    return True

if __name__ == '__main__':
    import sys
    from optparse import OptionParser

    parser = OptionParser(usage=__doc__)
    parser.add_option('-f', '--file',
                      help='play a list of IDs/URLs from FILE')
    parser.add_option('-i', '--id', action='append',
                      help='directly play an ID or URL')
    parser.add_option('-p', '--playlist', action='store_true', default=False,
                      help='build up a playlist to play/save')
    parser.add_option('-v', '--video', action='store_true', default=False,
                      help='play video(s) too')
    opts, args = parser.parse_args()

    if opts.playlist:
        juke()
    elif opts.file:
        if os.path.exists(opts.file):
           for vid in open(opts.file).readlines():
               mplayer(directvid(vid.strip()), opts.video)
    elif opts.id:
        for vid in opts.id:
            mplayer(directvid(vid), opts.video)
    else:
        if args:
            s = ' '.join(args)
        else:
            s = raw_input('search: ')
        if s:
            ls = search(s)
            while True:
                vid = choose(ls)
                if not vid:
                    break
                mplayer(directvid(vid), opts.video)
